# Plik makefile - make all do kompilacji wszystkiego
# Kompilacja pliku binaryTree

CC = gcc

all: binaryTree.o
	$(CC) binaryTree.o -o binaryTree.

binaryTree.o: binaryTree.c 
	$(CC) binaryTree.c 	-c -o binaryTree.o