#Makefile -make to compile everything
#Kompilation of readXML file

CC=clang

#all:readXML.o
#	$(CC) -lxml2 readXML.o
#
#readXML.o:
#	$(CC) -lxml2 readXML.c -o readXML.o

all:
	$(CC) -lxml2 readXML.c
